### ISSUE TITLE
AttributeError: 'str' object has no attribute 'focus_set'

### ISSUE THREAD

**Issue by AlbertSolomon** [AlbertSolomon/tubepy#14]
``` 
line 570, in <lambda> app.bind("<1>", lambda event: event.widget.focus_set())
AttributeError: 'str' object has no attribute 'focus_set'
```
This error occurs when switching between pages, its also a breaking change because it prevents hot reload during development, but does not crash the application.

**Comment by treecake10** [comment]
What exactly is being bound here or what is the '<1>'? Removing this line, the error goes away, and nothing seems to be affected on the surface.

**Comment by treecake10** [comment]
The hot reload issue still persists even removing the line

**Comment by AlbertSolomon** [comment]
@treecake10 👋 create Pull Request, because it's spitting out errors on my end.

**Comment by treecake10** [comment]
@AlbertSolomon How does this work on your end?

`def nextpage():
    global page_number, app
    for widget in app.winfo_children():
        widget.destroy()

    if page_number == 1:
        aboutTubepy(app)
        page_number = 2
    else:
        displayUI()
        app.bind("<1>", lambda event: event.widget.focus_set())
        page_number = 1`

**Comment by treecake10** [comment]
@AlbertSolomon instead of _app.bind_ why not _entry.bind_ like you have in the previous line for _<Button-3>_?

**Comment by AlbertSolomon** [comment]
@treecake10, Yeah, that makes sense 😅, Thanks again 🔥
