### ISSUE TITLE
Progress Bar Not Hiding After Download Completion

### ISSUE THREAD

**Issue by AlbertSolomon** [AlbertSolomon/tubepy#21]
The progress bar on the download page is not hiding after the download is completed. Once the download is finished, the progress bar remains visible, which can be confusing for users and may cause them to think that the download is still in progress. This issue is particularly problematic for users who download large files, as the progress bar may stay visible for a long time after the download is finished. The progress bar should disappear automatically once the download is complete to provide a clear indication that the process is finished.

**Comment by SahilDave04** [comment]
Hey!
Which file contains the progress bar?

**Comment by AlbertSolomon** [comment]
@SahilDave04 setup.py, but I decided to fix it 😅, you can try to depopulate the ``infobox `` widget 5 seconds after completing the download, so ill keep this is issue for now.
