### ISSUE TITLE
Download Gets Cancelled/Stopped When User Switches Pages

### ISSUE THREAD

**Issue by AlbertSolomon** [AlbertSolomon/tubepy#26]
When a user initiates a download and then switches to a different page, the download gets cancelled or stopped. This issue disrupts the download process, and users may need to restart the download from the beginning. This issue can be frustrating for users who have slow internet connections or who need to download large files, as it can take a long time to restart the download process. The download process should continue in the background even if the user switches pages to ensure that the download is not interrupted.

**Comment by treecake10** [comment]
might be good to have two separate functions for each page

**Comment by treecake10** [comment]
what about separating the _displayUI()_ function to where one function does the downloading process and one just builds the UI again so that instead of calling one big function in _nextPage_, only the UI rebuilds to somehow synchronize with the current downloading process

**Comment by treecake10** [comment]
or am I missing a simpler approach

**Comment by treecake10** [comment]
Yeah, I should have stated it's not a complete solution. Hopefully it will
be an easier fix.
