### ISSUE TITLE
Download isn't working for Youtube Shorts

### ISSUE THREAD

**Issue by Sjorza** [AlbertSolomon/tubepy#30]
If you want to download to a Youtube Short, Tubepy raises an error: _The url you have provided is not valid. Please verify it and try again._

Lang.py contains a definiton validate_youtube_url, but setup.py doesn't contain this definition.

**Comment by jdrysdaleandesrson** [comment]
Cant replicate this issue. New patch must have fixed it.

**Comment by AlbertSolomon** [comment]
@Sjorza 👋🏾 ``def validate_youtube_url(url) `` is implemented in ``async def file_verification(youtube_url)`` on line 160 in lang.py.

**Comment by Sjorza** [comment]
I'm sorry, I totally missed that. At this moment I'm having troubles to even open Tubepy to check again. I don't know what I'm doing wrong, but you can close this issue.

**Comment by AlbertSolomon** [comment]
@Sjorza 👋🏾 I've been trying to replicate this issue, and I was finally able to replicate it, there might be an issue with the regex, for instance, when someone sends me a YouTube from a mobile phone, YouTube has a default URL shortener which looks like so ``https://youtu.be/8RcP7BmUKaA`` while the original link of this URL looks like so ``https://www.youtube.com/watch?v=8RcP7BmUKaA``, notice the difference, YouTube replaces the original URL like this 
```diff
-www.youtube.com/watch?v=
+youtu.be/
```
Now in line number 122 in lang.py you will find this regex function. 😅 (emphasis on the comment lol!)
![regex issue](https://user-images.githubusercontent.com/48782826/230328176-a40ebdbe-93d4-4d06-b3a0-fce5cf7c86bf.png)

You can see in the acceptable URL list that ``youtu.be/`` is present, but still, it does not work, so we have to somehow do the replacing ourselves, to trick it so that the regex expression sees the original URL whenever it encounters a similar URL containing ``youtu.be``.

**Comment by AlbertSolomon** [comment]
@Sjorza please share the errors you are encountering, it will be very helpful.

**Comment by Sjorza** [comment]
I think I didn't open the virtual environment this morning. I think I wasn't awake. 😅 

I didn't encounter your problem with the regex function. My problem was in the search_file_availability function. It returned 302 instead of 200. I made a pull request on this issue.

**Comment by AlbertSolomon** [comment]
@Sjorza okay, if its 302 that means the file is not available 😅, ``https://youtu.be/8RcP7BmUKaA`` is going to troublesome because its a shortened version of the url 😅

**Comment by Sjorza** [comment]
I have tested a lot, but I believe this is a difficult problem. I have changed the file_verification like this:

```
async def file_verification(youtube_url) -> bool:
    """This relies on the search_file_availability function and the validate_youtube_url function to make sure the Youtube file is available."""

    validatd_url = validate_youtube_url(youtube_url)
    status = await search_file_Availability(youtube_url) if validatd_url else None

    if status == 200:
        return True

    if status != 200:
        async with aiohttp.ClientSession() as session:
            async with session.get(youtube_url, allow_redirects=False) as response:
                redirect_url = response.headers.get('Location')
                if redirect_url:
                    validatd_url = validate_youtube_url(redirect_url)
                    status = await search_file_Availability(redirect_url) if validatd_url else None
                    print(redirect_url)

                    if status == 200:
                        return True
                

    return False
```
The redirected URL is now also checked for availability. Then I've tested it with existing videos, non-existing videos and short URLs. These were the results:

```
Verifying URL: https://www.youtube.com/watch?v=12345678901
Result: True
https://www.youtube.com/watch?v=12345678901 has statuscode 200

Verifying URL: https://www.youtube.com/watch?v=12345678901234567890
Result: True
https://www.youtube.com/watch?v=12345678901234567890 has statuscode 200

Verifying URL: https://www.youtube.com/watch?v=dQw4w9WgXcQ
Result: True
https://www.youtube.com/watch?v=dQw4w9WgXcQ has statuscode 200

Verifying URL: https://www.youtube.com/watch?v=2Vv-BfVoq4g
Result: True
https://www.youtube.com/watch?v=2Vv-BfVoq4g has statuscode 200

Verifying URL: https://youtu.be/dQw4w9WgXcQ
https://www.youtube.com/watch?v=dQw4w9WgXcQ&feature=youtu.be
Result: True
https://youtu.be/dQw4w9WgXcQ has statuscode 303

Verifying URL: https://youtu.be/12345678901234567890
https://www.youtube.com/watch?v=12345678901234567890&feature=youtu.be
Result: True
https://youtu.be/12345678901234567890 has statuscode 303

Verifying URL: https://www.youtube.com/shorts/FJX5R0PYt8M
https://consent.youtube.com/m?continue=https%3A%2F%2Fwww.youtube.com%2Fshorts%2FFJX5R0PYt8M%3Fcbrd%3D1&gl=NL&m=0&pc=yt&cm=2&hl=nl&src=1
Result: False
https://www.youtube.com/shorts/FJX5R0PYt8M has statuscode 302
```
As I can see, there are two problems:
- Non-existing videos like `https://www.youtube.com/watch?v=12345678901234567890` are True, but are supposed to be False. The functions only check for correct HTTP statuscode and Youtube URL, but not for the content of the webpage. You have to check for words like 'Video unavailable' or something like that.
- Somehow the last tested URL `https://www.youtube.com/shorts/FJX5R0PYt8M` redirects to a consent.youtube.com URL. This returns false at the validate_youtube_url function.

**Comment by AlbertSolomon** [comment]
@Sjorza Thanks again for the effort, I see your point, what I can only think about now is to try to use a scrapper of some sort, it's a tricky one indeed.  😅

**Comment by jdrysdaleandesrson** [comment]
Do you think we could just recunstruct the URL if it dosent have youtube.com format.

**Comment by AlbertSolomon** [comment]
@jdrysdaleandesrson nice suggestion, and its going to be even faster, as in it won't slow down the app.
