### ISSUE TITLE
Populate the infobox when downloading videos from a playlist. 👾

### ISSUE THREAD

**Issue by AlbertSolomon** [AlbertSolomon/tubepy#39]
Playlist download progress has been fixed, what remains is to populate the ``infobox`` with the information of a playlist which is being downloaded. 🚀

**Comment by spoloxs** [comment]
Can you tell me the location for infobox ?

**Comment by spoloxs** [comment]
> Playlist download progress has been fixed, what remains is to populate the `infobox` with the information of a playlist which is being downloaded. rocket

Can you tell me the location for infobox ?
