### ISSUE TITLE
YouTube Video/Playlist Info Not Displayed When Switching Pages ℹ️

### ISSUE THREAD

**Issue by AlbertSolomon** [AlbertSolomon/tubepy#45]
The current implementation of the application does not display YouTube video or playlist information when a user switches back and forth between pages while a video is downloading. This can be frustrating for the user, as they may want to view the information while the download is in progress.

**🚀 Solution:** One possible solution to this issue is to store the YouTube video or playlist information in a global variable or cache, so that it can be accessed and displayed on any page at any time. This would provide a more consistent and informative user experience, and help to prevent frustration.

**Comment by klorine28** [comment]
hello could i get some more context on this issue?
