### ISSUE TITLE
Display errors in event_label() widget. 

### ISSUE THREAD

**Issue by AlbertSolomon** [AlbertSolomon/tubepy#85]
Display network connection and download errors/failure in the event_label() widget.

**Comment by klorine28** [comment]
hello can i get some more context on this issue please

**Comment by AlbertSolomon** [comment]
_@klorine28_ The event_label widget (or function) is commonly utilized to display errors and notify users about various events, such as loading codecs. However, it lacks the capability to effectively notify users when errors occur during the downloading of a file. This inconsistency becomes apparent as the widget fails to display any error message or notification when something goes wrong during the file download process. To enhance user experience and ensure comprehensive error handling, the event_label widget should be modified to consistently notify users whenever an error occurs, regardless of the specific nature of the error.

**Comment by klorine28** [comment]
So the enhancement is changing the code on the event_label() to make it consistent?

**Comment by AlbertSolomon** [comment]
@klorine28 Not really, but one effective approach is to maintain an error log and utilize the event_label() function to promptly display any errors that arise, irrespective of their occurrence within the project. This way, we can easily track and display the specific error(s) encountered during the execution of the project.
